name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-20.04-v4
    steps:
      - name: print greeting
        run: echo "hello world!"
      - name: Print goodbye
        run: echo "Done - bye!"
